services:
    laundryapp:
        build:
            args:
                user: laundryapp
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laundryapp:1.0.0
        container_name: laundryapp-container
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
        networks:
            - laundryapp
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 10s
            retries: 3

    mysql:
        image: mysql:8.0.27
        container_name: laundryapp-mysql-container
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            LANG: C.UTF-8
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - laundryapp
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

    nginx:
        image: nginx:alpine
        container_name: laundryapp-nginx-container
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laundryapp
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 10s
            retries: 3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laundryapp-phpmyadmin-container
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - laundryapp

networks:
    laundryapp:
        driver: bridge
